[package]
name = "volkanicmc-construct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
clap = { version = "4.4.8", features = ["derive"] }
copy_dir = "0.1.3"
flate2 = "1.0.28"
futures-util = "0.3.29"
hex = "0.4.3"
indicatif = "0.17.7"
reqwest = { version = "0.11.22", features = ["stream"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_jsonc = "1.0.108"
serde_yaml = "0.9.27"
sha2 = "0.10.8"
sysinfo = "0.29.10"
tar = "0.4.40"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
zip = "0.6.6"
