name: Release
on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
  PKG_NAME: "volkanicmc-construct"
  VERSION: "0.1.0"

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ${{ matrix.job.on }}
    strategy:
      matrix:
        job:
          - {
              arch: x86_64,
              target: x86_64-unknown-linux-gnu,
              on: ubuntu-20.04,
            }
          - {
              arch: aarch64,
              target: aarch64-unknown-linux-gnu,
              on: ubuntu-20.04,
            }
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: |
          sudo apt update
          sudo apt remove cargo rustc rust-doc
          if [[ "${{ matrix.job.arch }}" == "aarch64" ]]; then
            sudo apt install -y gcc-aarch64-linux-gnu
          fi
      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
      - name: Add Rust target
        run: |
          if [[ "${{ matrix.job.target }}" != "x86_64-unknown-linux-gnu" ]]; then
            rustup target add ${{ matrix.job.target }}
          fi
      - name: Show Rust version
        run: |
          cargo --version
          rustc --version
      - name: Install cargo-deb
        run: |
          cargo install cargo-deb
      - name: Build Debian package
        run: |
          cargo deb --profile release --target ${{ matrix.job.target }} -o target/${{ env.PKG_NAME }}.deb
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME }}_${{ env.VERSION }}-linux-${{ matrix.job.arch }}.deb
          path: target/${{ env.PKG_NAME }}.deb
