name: Deploy Images to GHCR

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
      stable:
        type: boolean
        required: true
      tag:
        type: string
        required: true
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'
  PUSH: ${{ inputs.push }}
  STABLE: ${{ inputs.stable }}
  TAG: ${{ inputs.tag }}

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 'Build and Push Docker Images'
        if: env.PUSH == 'true'
        run: |
          if [[ "${{ env.STABLE }}" == "true" ]]; then
            docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
              -t ghcr.io/8bitz0/vkconstruct:latest \
              -t ghcr.io/8bitz0/vkconstruct:stable \
              -t ghcr.io/8bitz0/vkconstruct:${{ env.TAG }} \
              -f ./containers/Containerfile.ubuntu \
              --push \
              .
          else
            docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
              -t ghcr.io/8bitz0/vkconstruct:latest \
              -t ghcr.io/8bitz0/vkconstruct:${{ env.TAG }} \
              -f ./containers/Containerfile.ubuntu \
              --push \
              .
          fi
