name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_run:
    workflows: [Rust]
    branches: [main]
    types: [completed]
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Set up Docker Buildx'
            uses: docker/setup-buildx-action@v2
            with:
              driver: docker-container

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_TOKEN}}

          - name: 'Build and Push Docker Images'
            run: |
              docker buildx build --platform linux/amd64,linux/arm64 \
                -t ghcr.io/user/vkconstruct:latest \
                -t ghcr.io/user/vkconstruct:ubuntu \
                -f ./containers/Containerfile.alpine \
                -f ./containers/Containerfile.ubuntu --push \
                .
