name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GHCR_TOKEN}}

          - name: 'Build and Push Docker Images'
            run: |
              docker build -t ghcr.io/8Bitz0/volkanicmc-construct:latest --target final -f ./containers/Containerfile.alpine .
              docker push ghcr.io/8Bitz0/volkanicmc-construct:latest
              docker build -t ghcr.io/8Bitz0/volkanicmc-construct:ubuntu --target final -f ./containers/Containerfile.ubuntu .
              docker push ghcr.io/8Bitz0/volkanicmc-construct:ubuntu
