name: Build on tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      publish: true
      upload-tag: ${{ github.ref_name }}
